before_script:
    - apt-get update

stages:
    - check
    - install

check:
    only:
        - master
    script:
        - make check

install:
    only:
        - master
    script:
        - echo echo "not implemented"