stages:
    - build
    - test
    - cleanup
    - deploy

build_job:
    stage: build
    script:
        - make

test_job:
    stage: test
    only:
        - master
    script:
        - make check

cleanup_job:
    stage: cleanup
    script:
        - make clean
    when: always

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - ssh ih1115@146.169.45.167 'ls -l'
    only: 
        - master
