stages:
    - build
    - test
    - cleanup
    - deploy

build_job:
    stage: build
    script:
        - make

test_job:
    stage: test
    only:
        - master
    script:
        - make check

cleanup_job:
    stage: cleanup
    script:
        - make clean
    when: always

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - rm database/fifo -f
        - chmod 600 id_rsa
        - ssh -i id_rsa -o StrictHostKeyChecking=no ih1115@146.169.45.167 'cd webapps_23 && make uninstall && cd .. && rm webapps_23 -rf'
        - scp -r -i id_rsa -o StrictHostKeyChecking=no . ih1115@146.169.45.167:~/webapps_23/
        - ssh -i id_rsa -o StrictHostKeyChecking=no ih1115@146.169.45.167 'cd webapps_23 && make install'
    only: 
        - master
