stages:
    - build
    - test
    - cleanup
    - deploy

build_job:
    stage: build
    script:
        - make

test_job:
    stage: test
    only:
        - master
    script:
        - make check

cleanup_job:
    stage: cleanup
    script:
        - make clean
    when: always

install_job:
    stage: deploy
    only:
        - master
    script:
        - make install
    when: manual