image: node:8.0.0

cache:
    untracked: true
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - react/my-app/node_modules/

stages:
    - build
    - test
    - cleanup
    - deploy

build_job:
    stage: build
    script:
        - ./depend.sh
        - make

test_job:
    stage: test
    only:
        - master
    script:
        - make check

cleanup_job:
    stage: cleanup
    script:
        - make clean
    when: always

deploy_job:
    stage: deploy
    only:
        - master
    script:
        - apt-get update && apt-get install -y netcat   # either this or make a seperate depend.sh for deploy
        - make pings