#!/bin/bash
# This file contains most deploy-specific constants.
# Note - this file is excluded by gitignore. Not recommented to commit.

# Gameserver relatdqwdwqdqwdqed constants
CW_GS_COMFLAGS=-O2
CW_GS_RUNFLAGS=-pass base -wait 10

# Database related constants
CW_PORT=
CW_MYADDR=
CW_SERVPATH=
CW_SERVPASS=base
