CREATE USER "cellwarsuser" WITH LOGIN NOSUPERUSER CREATEDB NOCREATEROLE NOINHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD '123';
CREATE DATABASE cellwars WITH OWNER = cellwarsuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;
