DROP DATABASE cellwars;
DROP USER "cellwarsuser";

CREATE USER "cellwarsuser" WITH LOGIN NOSUPERUSER CREATEDB NOCREATEROLE NOINHERIT NOREPLICATION CONNECTION LIMIT -1 PASSWORD 'EXps4YvVt85hXpMSutP';
CREATE DATABASE cellwars WITH OWNER = cellwarsuser ENCODING = 'UTF8' CONNECTION LIMIT = -1;
